version: '3.9'

services:

  db:
    restart: always
    image: postgres:14.4-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-cs:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=d5h9rt0bramqit
      - POSTGRES_USER=nzqbbumitkvvvk
      - POSTGRES_PASSWORD=38a98195b94a7415b10e50277dfea3d32333505b4996aa1a4295725d3f702b47

  api:
    restart: always
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app_rest
    depends_on:
      - db
    # environment:
    #   - DB_NAME=csdb
    #   - DB_USER=csuser
    #   - DB_PASSWORD=Admin141189@
    #   - DB_HOST=postgres

volumes:
  db-cs: